data:
  dataset_name: "domfountain_station2"
  raw_file_path: "data/domfountain_station2_xyz_intensity_rgb.txt"

voxelization:
  method: "rnn" # radius nearest neighbor
  radius: 0.1
  output_file: "results/voxels.ply"

classification:
  classes:
    - "Building"
    - "Tree"
    - "Pole"
    - "Car"
    - "Ground"
